feat: create bank smart contract
globe-and-citizen/cnc-portal pull request #129
Opened 2024-05-26 05:54 UTC by farrellh1

# Description

create banking smart contract

Fixes # (#124)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)

2024-05-27 10:50 UTC, hermannleboss commented
@farrellh1 can you create all the bank account.

2024-05-27 14:27 UTC, farrellh1 commented
idk why the ci cd not running

2024-05-27 20:41 UTC, hermannleboss commented
> idk why the ci cd not running

The CI CD run depending on what file is updated

2024-05-27 20:44 UTC, hermannleboss commented
For the moment the CI CD for the contract run only on PR on develop and main branch

2024-05-31 09:54 UTC, hermannleboss requested changes

2024-05-31 09:54 UTC, hermannleboss commented on contract/test/Bank.spec.ts
Can you look at this for the test structure. 
https://dev.to/walmyrlimaesilv/using-the-keywords-given-when-then-with-cypress-but-without-cucumber-118p

It's about cypress but it work with most test framework.

2024-05-31 11:54 UTC, farrellh1 commented on contract/test/Bank.spec.ts
i see, it's like a user stories, right?

2024-05-31 11:56 UTC, farrellh1 commented on contract/test/Bank.spec.ts
i was following how Uniswap testing their smart contract

2024-06-01 08:46 UTC, farrellh1 commented
i applied your suggestion @hermannleboss , but it reduce the code coverage

2024-06-03 16:01 UTC, hermannleboss requested changes
Take the user Stories in the context of the bank.

2024-06-03 16:01 UTC, hermannleboss commented on contract/test/Bank.spec.ts
> +
It's from there i remark you are using the user Stories i create for the CNC portal to make the test. 
Let me tell you that there is a difference between the userStories in the context of the CNC and in the context of the Bank Smart contract

2024-06-03 16:33 UTC, hermannleboss commented
> > r Stories of the Bank Smart Contract
> 
> should i revise all the testing to be like your suggestion instead @hermannleboss ? or just adjust some of them to be like you mentioned here?

You should refactor you test to the new useStories. You adjust what i wrote.

2024-06-03 16:56 UTC, farrellh1 commented
applied @hermannleboss , thanks

2024-06-03 17:32 UTC, hermannleboss approved these changes
LGTM

2024-06-03 17:43 UTC, merged