feat: implement notifications pagination for frontend
globe-and-citizen/cnc-portal pull request #212
Opened 2024-06-21 01:13 UTC by dasarathg68

# Description

Fixes #211 
Solution:
    - Added Next and Previous buttons to navigate.
    - Display the current page number and total pages in the dropdown.
    - display a limited number of notifications per page (10).
    
Video Demo: 
https://github.com/globe-and-citizen/cnc-portal/assets/31665486/1390c2ea-6d28-47e7-a38b-7417dcad6f1a

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

2024-06-21 11:41 UTC, hermannleboss requested changes
Can you move all the notification in a component ?

2024-06-21 11:41 UTC, hermannleboss commented on app/src/views/TeamView.vue
I don't get why you need this.

2024-06-21 16:10 UTC, dasarathg68 commented
@hermannleboss moved the notifications to a separate component. Please check

2024-06-24 10:08 UTC, hermannleboss approved these changes

2024-06-24 10:08 UTC, merged