fix: accordion v-model
globe-and-citizen/cnc-portal pull request #260
Opened 2024-07-13 06:13 UTC by farrellh1

# Description

Fix accordion not follow how the radio button works 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)

2024-07-13 11:17 UTC, hermannleboss requested changes

2024-07-13 11:17 UTC, hermannleboss commented on app/src/components/__tests__/AccordionComponent.spec.ts
Hello @farrellh1 
About the test last time i was talking about how you can create test for a component where when you edit the component without changing the behaviour of your component, you should not need to update the test. 

In your case you are finding element 'input[type="radio"]' 

Let say in the future, we decide to change the radio input buy a button. And storing the variable of the active state. 

The behaviour don't change, but because we change the implementation you have also to change the test.

2024-07-13 11:17 UTC, hermannleboss commented on app/src/components/__tests__/AccordionComponent.spec.ts
For this you can use data-test for the selector.

look at this file https://github.com/globe-and-citizen/cnc-portal/blob/develop/app/src/components/forms/__tests__/AddMemberForm.spec.ts

2024-07-15 05:57 UTC, dasarathg68 approved these changes
LGTM

2024-07-15 11:38 UTC, farrellh1 commented on app/src/components/__tests__/AccordionComponent.spec.ts
I see, but I haven't added the emits test for `AccordionComponent` before, it should be added in the accordion component PR but I forgot. so I added here

2024-07-16 10:02 UTC, hermannleboss commented on app/src/components/__tests__/AccordionComponent.spec.ts
Yes but now i'm requesting you refactor the test to follow the rule.

The selector you used for the test in not good and can lead into unnecessary error.

2024-07-16 12:39 UTC, farrellh1 commented on app/src/components/__tests__/AccordionComponent.spec.ts
i applied your suggestion, please check thanks

2024-07-16 12:47 UTC, hermannleboss approved these changes

2024-07-16 12:47 UTC, merged