Feat/form validation
globe-and-citizen/cnc-portal pull request #275
Opened 2024-07-23 14:22 UTC by aliassan

# Description

Adds form validation using Vuelidate on teams.

Fixes #250 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

2024-07-24 06:27 UTC, hermannleboss requested changes
It's look good but your test are failing

2024-07-27 16:04 UTC, hermannleboss requested changes

2024-07-27 16:04 UTC, hermannleboss commented on app/src/components/forms/AddTeamForm.vue
> +})
Why this have hard coded data ?

2024-07-27 16:04 UTC, hermannleboss commented on app/src/components/forms/__tests__/AddTeamForm.spec.ts
> +  })*/
Why you remove the check of the Emit ?

2024-07-27 16:04 UTC, hermannleboss commented on app/src/components/forms/__tests__/AddTeamFormValidation.spec.ts
Normaly you can add this part into AddTeamForm.spec.ts

2024-07-28 11:41 UTC, dasarathg68 commented on app/src/components/forms/AddTeamForm.vue
> +const $v = useVuelidate(rules, { team })
This might introduce conflicts don't you think?
The $ prefix is reserved for internal Vue utilities.

2024-07-28 11:42 UTC, dasarathg68 commented
I think this looks good!
Simple and easy to use.

2024-07-30 15:05 UTC, hermannleboss approved these changes
LGTM

2024-07-30 15:05 UTC, merged