fix/handle error when metamask not installed
globe-and-citizen/cnc-portal pull request #83
Opened 2024-05-08 11:19 UTC by dasarathg68

# Description

Fixes #77 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

* **Please check if the PR fulfills these requirements**

- [x] The commit message follows our guidelines

2024-05-08 12:13 UTC, hermannleboss commented
@dasarathg68 i add accepatance criteria on this

2024-05-08 12:26 UTC, hermannleboss requested changes

2024-05-08 12:26 UTC, hermannleboss commented on app/src/adapters/web3LibraryAdapter.ts
Every time you call the function connectWallet you can have an error throw new Error('Wallet is not connected')
Need more test about how the error is handle and what are the error we can have

2024-05-09 17:12 UTC, farrellh1 commented
u can use new library in #75

2024-05-16 22:10 UTC, hermannleboss approved these changes
LGTM

2024-05-16 22:10 UTC, merged